apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  endpoints:
  - port: prometheus  # Use the "prometheus" port defined in your deployment
    path: /metrics    # The default metrics path for NGINX Ingress
    interval: 15s
  namespaceSelector:
    matchNames:
    - ingress-nginx
